/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TestimonialCardLazyImport = createFileRoute('/testimonial-card')()
const BlogCardLazyImport = createFileRoute('/blog-card')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TestimonialCardLazyRoute = TestimonialCardLazyImport.update({
  id: '/testimonial-card',
  path: '/testimonial-card',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/testimonial-card.lazy').then((d) => d.Route),
)

const BlogCardLazyRoute = BlogCardLazyImport.update({
  id: '/blog-card',
  path: '/blog-card',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/blog-card.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/blog-card': {
      id: '/blog-card'
      path: '/blog-card'
      fullPath: '/blog-card'
      preLoaderRoute: typeof BlogCardLazyImport
      parentRoute: typeof rootRoute
    }
    '/testimonial-card': {
      id: '/testimonial-card'
      path: '/testimonial-card'
      fullPath: '/testimonial-card'
      preLoaderRoute: typeof TestimonialCardLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/blog-card': typeof BlogCardLazyRoute
  '/testimonial-card': typeof TestimonialCardLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/blog-card': typeof BlogCardLazyRoute
  '/testimonial-card': typeof TestimonialCardLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/blog-card': typeof BlogCardLazyRoute
  '/testimonial-card': typeof TestimonialCardLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog-card' | '/testimonial-card'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog-card' | '/testimonial-card'
  id: '__root__' | '/' | '/blog-card' | '/testimonial-card'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BlogCardLazyRoute: typeof BlogCardLazyRoute
  TestimonialCardLazyRoute: typeof TestimonialCardLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BlogCardLazyRoute: BlogCardLazyRoute,
  TestimonialCardLazyRoute: TestimonialCardLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog-card",
        "/testimonial-card"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/blog-card": {
      "filePath": "blog-card.lazy.tsx"
    },
    "/testimonial-card": {
      "filePath": "testimonial-card.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
